fix: Missing keyboard accessibility for AI toolbar button functionality
dxpr/ckeditor5-ai-agent pull request #69
Opened 2024-12-19 21:52 UTC by syuzanvs

- Updated the keyboard event listener in the `AiAgentUI` class to improve the handling of the AI Agent command execution.
- The shortcut for executing the command has been refined to ensure better responsiveness and user experience.
- Added a check for the `event` parameter in the `keydown` event listener to ensure that the command is executed only when the specified key combination (Ctrl + /) is pressed.

Closes #61

2024-12-20 08:34 UTC, jjroelofs requested changes
## Wrong key-shortcut implementation

The issue specified ctrl/CMD + / is the required keystroke combination, this means ctrl on Windows and CMD on MacOS. This is the convention in CKEditor and the OS difference is handled automatically by the CK5 API:

https://ckeditor.com/docs/ckeditor5/latest/framework/tutorials/crash-course/keystrokes.html

By using a custom keystrokes implementation we end up with a behavior not conforming to the set requirements.

## Add, not replace a shortcut

`ctrl/cmd + /` and `/` are two different features and we need to keep both in the accessibility panel. The slash is the keystroke to enter a AI command in an empty element, ctrl/cmd+/ is a more specialized combination to force a slash command inside a pre-existing text. Im not sure what description text to use, pls optimize this with your LLM of choice (ask the LLM to be an expert microcopy writer and UX researcher).

## Grouping

We can't have 3 AI commands spread all over the panel, they should be grouped in an AI Agent group.

2024-12-20 17:11 UTC, syuzanvs commented
> ## Wrong key-shortcut implementation
> The issue specified `ctrl/CMD + /` is the required keystroke combination, this means `ctrl` on Windows and `CMD` on MacOS. This is the convention in CKEditor and the OS difference is handled automatically by the CK5 API:
> 
> https://ckeditor.com/docs/ckeditor5/latest/framework/tutorials/crash-course/keystrokes.html
> 
> By using a custom keystrokes implementation we end up with a behavior not conforming to the set requirements.
> 
> ## Add, not replace a shortcut
> `ctrl/cmd + /` and `/` are two different features and we need to keep both in the accessibility panel. The singular `/` is the keystroke to enter a AI command in an empty element, `ctrl/CMD+/ `is a more specialized combination to force a slash command inside a pre-existing text. Im not sure what description text to use, pls optimize this description text in the Accessibility Help panel with your LLM of choice (ask the LLM to be an expert microcopy writer and UX researcher).
> 
> ## Grouping
> We can't have 3 AI Agent commands spread all over the panel, they should be grouped in an AI Agent group.

@jjroelofs
The "keystrokes " didn't work for exactly command `ctrl/CMD + /`. I was not sure why, and that's the reason I got it done differently. But will recheck again to see what's the reason of the issue

2024-12-24 19:56 UTC, syuzanvs commented
@jjroelofs  
https://ckeditor.com/docs/ckeditor5/latest/framework/tutorials/crash-course/keystrokes.html
regarding you comment for this documentation, with this method it supports `Ctrl+Alt+H` but it doesn't support `Ctrl+/` . 
With my new change now our code should support MacOS but I'll need to ask you to test it

2024-12-27 13:54 UTC, jjroelofs requested changes
I updated the keyboard shortcut descriptions and it is now looking good. However, the cancelation shortcut is not working for me. Click the cancel button works, using the keyboard shortcut does not. Not sure if it is a recent regression or we just didn't test it well before.

2025-01-02 20:30 UTC, syuzanvs commented
@jjroelofs the cancelation works for me, was not able to reproduce an issue with that. 
If you can pls review again and let me know if you get it and how to reproduce. We can have a separate task for it if you are able to get the issue

2025-01-06 13:20 UTC, jjroelofs approved these changes
Great! And I cannot reproduce the failing cancel button anymore. Will create a new issue if it comes back :)

2025-01-06 13:21 UTC, merged